# Generated by Django 3.2 on 2021-04-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, null=True, verbose_name='Descripción')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Precio')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('dimensiones', models.CharField(max_length=100, verbose_name='Dimensiones')),
                ('disponible', models.CharField(choices=[('sí', 'sí'), ('no', 'no')], default='sí', max_length=2, verbose_name='Disponible')),
            ],
        ),
    ]
